version: '3'
services:
  api:
    container_name: api
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - .:/api
    ports:
      - "3000:3000" # web/API
      - "9229:9229" # debug
    command: "node --inspect=0.0.0.0:9229 --nolazy /api/bin/www"
